siteTitle = 'Irukanji'
siteDescr = 'Psychedelic Electronica'

siteBandcampUrl = 'https://irukanji.bandcamp.com'
siteSoundcloudUrl = 'https://soundcloud.com/irukanji-music'
siteFacebookUrl = 'https://www.facebook.com/irukanji.music'
siteDiscogsUrl = 'http://www.discogs.com/artist/1375976-Irukanji'
siteTwitterUrl = 'https://twitter.com/irukanji_music'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/irukanji-music'

linkPrefix = ''
